### ISSUE TITLE
Migrate to Node.js 16

### ISSUE THREAD

**Issue by m8mble** [seanmiddleditch/gha-setup-ninja#16]
First of all, thanks for this great action.

When using it (e.g. [here](https://github.com/clean-test/clean-test/actions/runs/3383553086)), I lately started to see the following warnings:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: seanmiddleditch/gha-setup-ninja

> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

It would be great to get a new release, that works both with the updated Node.js as well as without any warnings.

**Comment by IGR2014** [comment]
Same in my CI\CD pipeline

**Comment by IGR2014** [comment]
Should be fixed ASAP because: https://github.com/actions/runner-images/issues/6482

**Comment by offa** [comment]
There's a pending PR: #15

**Comment by LukasSkywalker** [comment]
> Should be fixed ASAP because: [actions/runner-images#6482](https://github.com/actions/runner-images/issues/6482)

Actions can still use Node 12: https://github.com/actions/runner-images/issues/6482#issuecomment-1308321658

**Comment by seanmiddleditch** [comment]
Merged https://github.com/seanmiddleditch/gha-setup-ninja/pull/15 which closes this.
