### ISSUE TITLE
Pre-defined proxy in code?

### ISSUE THREAD

**Issue by elcuco** [seanmiddleditch/gha-setup-ninja#18]
https://github.com/seanmiddleditch/gha-setup-ninja/blob/master/index.js#L10

This code shows an IP for a proxy... it seems unused right?

**Comment by seanmiddleditch** [comment]
I should have commented what that was from. It shows up in some old GitHub docs, so it might have been the internal proxy Actions required at the time I wrote it?

**Comment by seanmiddleditch** [comment]
Removed now thanks to #27
