### ISSUE TITLE
Wrong record in PATH variable.

### ISSUE THREAD

**Issue by spacemaze** [seanmiddleditch/gha-setup-ninja#2]
I noticed, that it doesn't put full path to binary into PATH, but rather just a *filename*.
Here is my path after "Setup Ninja" step:
```
PATH=ninja_bin:/Users/runner/.cargo/bin:/usr/local/lib/ruby/gems/2.6.0/bin:/usr/local/opt/ruby/bin:/usr/local/opt/curl/bin:/usr/local/bin:/usr/local/sbin:/Users/runner/bin:/Users/runner/.yarn/bin:/usr/local/go/bin:/Users/runner/Library/Android/sdk/tools:/Users/runner/Library/Android/sdk/platform-tools:/Users/runner/Library/Android/sdk/ndk-bundle:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/bin:/bin:/usr/sbin:/sbin:/Users/runner/.dotnet/tools:/Users/runner/.ghcup/bin:/Users/runner/hostedtoolcache/stack/2.3.1/x64
```
[Link to my YAML file (frozen)](https://github.com/spacemaze/cppl/blob/f9f4a837526402ca1636b6cc0df685808c2066a1/.github/workflows/c-cpp.yml)

Thanks!

I think when you add it to path, for Posix OSs you should use something like (quotes matter):
```bash
  export PATH="$PWD/ninja_bin:$PATH"
```

**Comment by seanmiddleditch** [comment]
Hmm, this is working properly on all my CI builds with no need to modify the `PATH` after the fact. Will add some tests and see if I can get to the bottom of this.

**Comment by seanmiddleditch** [comment]
This doesn't seem to repro with the tests here. On all three supported environments (Windows, Mac, Ubuntu) the absolute path of the `ninja-build` directory is added to the `PATH`.

I'm closing this out, but if you have more info or a minimal repro case I'd be super interested to figure out what you are running into with this action!
